[package]
name = "ori-embed"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
ori-codegen = { workspace = true }
ori-diagnostics = { workspace = true }
ori-driver = { workspace = true }
ori-hir = { workspace = true }
ori-types = { workspace = true }
thiserror = { workspace = true }
