use ori_hir::{HirFunc, HirModule, HirStruct};
use ori_types::{DefId, Ty};
use std::collections::{HashMap, HashSet};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum CExportStructKind {
    ScalarBridge,
    OpaqueHandle,
}

#[derive(Clone, Debug)]
struct CExportStruct {
    c_name: String,
    kind: CExportStructKind,
}

/// Render the public C declarations for a shared library built by
/// `ori compile --lib`.
pub fn generate_c_header(module: &HirModule, header_file_name: &str) -> Result<String, String> {
    let exports: Vec<&HirFunc> = module
        .funcs
        .iter()
        .filter(|function| function.c_export_name.is_some())
        .collect();
    let exported_structs = collect_exported_structs(module, &exports)?;
    let guard = header_guard(header_file_name);

    let mut header = String::new();
    header.push_str("/* Generated by Ori. Do not edit manually. */\n");
    header.push_str(&format!("#ifndef {guard}\n#define {guard}\n\n"));
    header.push_str("#include <stdbool.h>\n#include <stdint.h>\n\n");
    header.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");
    header.push_str("/* Ori runtime lifecycle and managed-value ownership. */\n");
    header.push_str("int32_t ori_rt_init(void);\n");
    header.push_str("void __ori_module_init(void);\n");
    header.push_str("void ori_rt_shutdown(void);\n");
    header.push_str("void ori_arc_retain(void *value);\n");
    header.push_str("void ori_arc_release(void *value);\n");

    if exports.iter().any(|function| {
        function
            .params
            .iter()
            .any(|parameter| matches!(parameter.ty, Ty::Result(_, _)))
            || matches!(function.return_ty, Ty::Result(_, _))
    }) {
        header.push_str(
            "\ntypedef enum OriResultTag {\n\
             \x20   ORI_RESULT_ERR = 0,\n\
             \x20   ORI_RESULT_OK = 1\n\
             } OriResultTag;\n",
        );
    }

    if !exported_structs.is_empty() {
        header.push('\n');
        render_struct_declarations(module, &exported_structs, &mut header)?;
    }

    if !exports.is_empty() {
        header.push_str("\n/* Functions exported with @c_export. */\n");
        for function in exports {
            render_function_declaration(function, &exported_structs, &mut header)?;
        }
    }

    header.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n");
    header.push_str(&format!("#endif /* {guard} */\n"));
    Ok(header)
}

fn collect_exported_structs(
    module: &HirModule,
    exports: &[&HirFunc],
) -> Result<HashMap<DefId, CExportStruct>, String> {
    let mut ordered_ids = Vec::new();
    let mut seen = HashSet::new();
    for function in exports {
        for ty in function
            .params
            .iter()
            .map(|parameter| &parameter.ty)
            .chain(std::iter::once(&function.return_ty))
        {
            collect_exported_struct_ids(ty, &function.name, &mut ordered_ids, &mut seen)?;
        }
    }

    let structs_by_id: HashMap<DefId, &HirStruct> = module
        .structs
        .iter()
        .map(|structure| (structure.def_id, structure))
        .collect();
    let mut kinds = HashMap::new();
    let mut short_name_counts = HashMap::<String, usize>::new();
    for def_id in &ordered_ids {
        let structure = structs_by_id.get(def_id).ok_or_else(|| {
            format!("cannot generate a C header: exported struct {def_id:?} is missing from HIR")
        })?;
        let kind = classify_exported_struct(structure)?;
        kinds.insert(*def_id, kind);
        *short_name_counts
            .entry(short_c_struct_name(&structure.name, kind))
            .or_default() += 1;
    }

    let mut exported_structs = HashMap::new();
    let mut emitted_names = HashSet::new();
    for def_id in ordered_ids {
        let structure = structs_by_id[&def_id];
        let kind = kinds[&def_id];
        let short_name = short_c_struct_name(&structure.name, kind);
        let name = if short_name_counts[&short_name] == 1 {
            short_name
        } else {
            qualified_c_struct_name(&structure.name, kind)
        };
        if !emitted_names.insert(name.clone()) {
            return Err(format!(
                "cannot generate a unique C type name for exported struct `{}`",
                structure.name
            ));
        }
        exported_structs.insert(def_id, CExportStruct { c_name: name, kind });
    }
    Ok(exported_structs)
}

fn collect_exported_struct_ids(
    ty: &Ty,
    function_name: &str,
    ordered_ids: &mut Vec<DefId>,
    seen: &mut HashSet<DefId>,
) -> Result<(), String> {
    match ty {
        Ty::Named(def_id, args) => {
            if !args.is_empty() {
                return Err(format!(
                    "cannot generate a C header for generic export type in `{function_name}`"
                ));
            }
            if seen.insert(*def_id) {
                ordered_ids.push(*def_id);
            }
        }
        Ty::Optional(inner) => {
            collect_exported_struct_ids(inner, function_name, ordered_ids, seen)?;
        }
        Ty::Result(ok, err) => {
            collect_exported_struct_ids(ok, function_name, ordered_ids, seen)?;
            collect_exported_struct_ids(err, function_name, ordered_ids, seen)?;
        }
        _ => {}
    }
    Ok(())
}

fn classify_exported_struct(structure: &HirStruct) -> Result<CExportStructKind, String> {
    if structure.fields.is_empty() {
        return Err(format!(
            "cannot generate a C header for empty exported struct `{}`",
            structure.name
        ));
    }
    if structure
        .fields
        .iter()
        .all(|field| is_c_export_scalar_field_ty(&field.ty))
    {
        Ok(CExportStructKind::ScalarBridge)
    } else {
        Ok(CExportStructKind::OpaqueHandle)
    }
}

fn render_struct_declarations(
    module: &HirModule,
    exported_structs: &HashMap<DefId, CExportStruct>,
    header: &mut String,
) -> Result<(), String> {
    for structure in module
        .structs
        .iter()
        .filter(|structure| exported_structs.contains_key(&structure.def_id))
    {
        let exported = &exported_structs[&structure.def_id];
        match exported.kind {
            CExportStructKind::ScalarBridge => {
                header.push_str(&format!("typedef struct {} {{\n", exported.c_name));
                let mut field_names = HashSet::new();
                for field in &structure.fields {
                    let c_type = direct_c_type(&field.ty)?;
                    let field_name = unique_c_identifier(&field.name, &mut field_names);
                    header.push_str(&format!("    {c_type} {field_name};\n"));
                }
                header.push_str(&format!("}} {};\n\n", exported.c_name));
            }
            CExportStructKind::OpaqueHandle => {
                header.push_str(&format!(
                    "typedef struct {} {};\n\n",
                    exported.c_name, exported.c_name
                ));
            }
        }
    }
    if header.ends_with("\n\n") {
        header.pop();
    }
    Ok(())
}

fn render_function_declaration(
    function: &HirFunc,
    exported_structs: &HashMap<DefId, CExportStruct>,
    header: &mut String,
) -> Result<(), String> {
    if c_export_return_transfers_managed_value(&function.return_ty, exported_structs) {
        header.push_str(
            "/* Caller owns each active managed return; release it with ori_arc_release(). */\n",
        );
    }

    let struct_return = named_exported_struct(&function.return_ty, exported_structs);
    let return_type = match &function.return_ty {
        Ty::Optional(_) => "bool".to_owned(),
        Ty::Result(_, _) => "OriResultTag".to_owned(),
        _ => match struct_return {
            Some(structure) if structure.kind == CExportStructKind::ScalarBridge => {
                "void".to_owned()
            }
            Some(structure) => format!("{} *", structure.c_name),
            None => direct_c_type(&function.return_ty)?.to_owned(),
        },
    };
    let export_name = function
        .c_export_name
        .as_deref()
        .ok_or_else(|| format!("missing C export name for `{}`", function.name))?;
    if c_identifier(export_name) != export_name {
        return Err(format!(
            "cannot generate a C header for non-portable export symbol `{export_name}`"
        ));
    }

    let mut parameters = Vec::with_capacity(function.params.len() + 2);
    let mut parameter_names = HashSet::new();
    for parameter in &function.params {
        render_parameter_declarations(
            &parameter.name,
            &parameter.ty,
            exported_structs,
            &mut parameter_names,
            &mut parameters,
        )?;
    }
    if let Some(structure) =
        struct_return.filter(|structure| structure.kind == CExportStructKind::ScalarBridge)
    {
        let out_name = unique_c_identifier("out", &mut parameter_names);
        parameters.push(format!("{} *{out_name}", structure.c_name));
    }
    match &function.return_ty {
        Ty::Optional(inner) => render_payload_out_declaration(
            "out",
            inner,
            exported_structs,
            &mut parameter_names,
            &mut parameters,
        )?,
        Ty::Result(ok, err) => {
            if !matches!(**ok, Ty::Void) {
                render_payload_out_declaration(
                    "ok_out",
                    ok,
                    exported_structs,
                    &mut parameter_names,
                    &mut parameters,
                )?;
            }
            if !matches!(**err, Ty::Void) {
                render_payload_out_declaration(
                    "error_out",
                    err,
                    exported_structs,
                    &mut parameter_names,
                    &mut parameters,
                )?;
            }
        }
        _ => {}
    }
    if parameters.is_empty() {
        parameters.push("void".to_owned());
    }

    header.push_str(&format!(
        "{}({});\n",
        c_declaration(&return_type, export_name),
        parameters.join(", ")
    ));
    Ok(())
}

fn render_parameter_declarations(
    source_name: &str,
    ty: &Ty,
    exported_structs: &HashMap<DefId, CExportStruct>,
    parameter_names: &mut HashSet<String>,
    parameters: &mut Vec<String>,
) -> Result<(), String> {
    match ty {
        Ty::Optional(inner) => {
            let tag_name =
                unique_c_identifier(&format!("{source_name}_has_value"), parameter_names);
            parameters.push(format!("bool {tag_name}"));
            render_payload_parameter_declaration(
                &format!("{source_name}_value"),
                inner,
                exported_structs,
                parameter_names,
                parameters,
            )
        }
        Ty::Result(ok, err) => {
            let tag_name = unique_c_identifier(&format!("{source_name}_tag"), parameter_names);
            parameters.push(format!("OriResultTag {tag_name}"));
            if !matches!(**ok, Ty::Void) {
                render_payload_parameter_declaration(
                    &format!("{source_name}_ok"),
                    ok,
                    exported_structs,
                    parameter_names,
                    parameters,
                )?;
            }
            if !matches!(**err, Ty::Void) {
                render_payload_parameter_declaration(
                    &format!("{source_name}_error"),
                    err,
                    exported_structs,
                    parameter_names,
                    parameters,
                )?;
            }
            Ok(())
        }
        _ => render_payload_parameter_declaration(
            source_name,
            ty,
            exported_structs,
            parameter_names,
            parameters,
        ),
    }
}

fn render_payload_parameter_declaration(
    source_name: &str,
    ty: &Ty,
    exported_structs: &HashMap<DefId, CExportStruct>,
    parameter_names: &mut HashSet<String>,
    parameters: &mut Vec<String>,
) -> Result<(), String> {
    let name = unique_c_identifier(source_name, parameter_names);
    let declaration = if let Some(structure) = named_exported_struct(ty, exported_structs) {
        format!("const {} *{name}", structure.c_name)
    } else {
        c_declaration(direct_c_type(ty)?, &name)
    };
    parameters.push(declaration);
    Ok(())
}

fn render_payload_out_declaration(
    source_name: &str,
    ty: &Ty,
    exported_structs: &HashMap<DefId, CExportStruct>,
    parameter_names: &mut HashSet<String>,
    parameters: &mut Vec<String>,
) -> Result<(), String> {
    let name = unique_c_identifier(source_name, parameter_names);
    let declaration = if let Some(structure) = named_exported_struct(ty, exported_structs) {
        match structure.kind {
            CExportStructKind::ScalarBridge => format!("{} *{name}", structure.c_name),
            CExportStructKind::OpaqueHandle => format!("{} **{name}", structure.c_name),
        }
    } else {
        c_declaration(direct_c_type(ty)?, &format!("*{name}"))
    };
    parameters.push(declaration);
    Ok(())
}

fn c_export_return_transfers_managed_value(
    ty: &Ty,
    exported_structs: &HashMap<DefId, CExportStruct>,
) -> bool {
    match ty {
        Ty::String => true,
        Ty::Named(_, _) => named_exported_struct(ty, exported_structs)
            .is_some_and(|structure| structure.kind == CExportStructKind::OpaqueHandle),
        Ty::Optional(inner) => c_export_return_transfers_managed_value(inner, exported_structs),
        Ty::Result(ok, err) => {
            c_export_return_transfers_managed_value(ok, exported_structs)
                || c_export_return_transfers_managed_value(err, exported_structs)
        }
        _ => false,
    }
}

fn named_exported_struct<'a>(
    ty: &Ty,
    exported_structs: &'a HashMap<DefId, CExportStruct>,
) -> Option<&'a CExportStruct> {
    let Ty::Named(def_id, args) = ty else {
        return None;
    };
    args.is_empty()
        .then(|| exported_structs.get(def_id))
        .flatten()
}

fn direct_c_type(ty: &Ty) -> Result<&'static str, String> {
    match ty {
        Ty::Bool => Ok("bool"),
        Ty::Int | Ty::Int64 => Ok("int64_t"),
        Ty::Int8 => Ok("int8_t"),
        Ty::Int16 => Ok("int16_t"),
        Ty::Int32 => Ok("int32_t"),
        Ty::U8 => Ok("uint8_t"),
        Ty::U16 => Ok("uint16_t"),
        Ty::U32 => Ok("uint32_t"),
        Ty::U64 => Ok("uint64_t"),
        Ty::Float | Ty::Float64 => Ok("double"),
        Ty::Float32 => Ok("float"),
        Ty::String => Ok("const char *"),
        Ty::Void => Ok("void"),
        unsupported => Err(format!(
            "cannot generate a C header for unsupported export type `{unsupported:?}`"
        )),
    }
}

fn c_declaration(c_type: &str, identifier: &str) -> String {
    let separator = if c_type.ends_with('*') { "" } else { " " };
    format!("{c_type}{separator}{identifier}")
}

fn is_c_export_scalar_field_ty(ty: &Ty) -> bool {
    matches!(
        ty,
        Ty::Bool
            | Ty::Int
            | Ty::Int8
            | Ty::Int16
            | Ty::Int32
            | Ty::Int64
            | Ty::U8
            | Ty::U16
            | Ty::U32
            | Ty::U64
            | Ty::Float
            | Ty::Float32
            | Ty::Float64
    )
}

fn short_c_struct_name(qualified_name: &str, kind: CExportStructKind) -> String {
    let short_name = qualified_name.rsplit('.').next().unwrap_or(qualified_name);
    let suffix = match kind {
        CExportStructKind::ScalarBridge => "",
        CExportStructKind::OpaqueHandle => "Handle",
    };
    format!("Ori{}{suffix}", pascal_case_identifier(short_name))
}

fn qualified_c_struct_name(qualified_name: &str, kind: CExportStructKind) -> String {
    let mut name = String::from("Ori");
    for component in qualified_name.split('.') {
        name.push_str(&pascal_case_identifier(component));
    }
    if kind == CExportStructKind::OpaqueHandle {
        name.push_str("Handle");
    }
    name
}

fn pascal_case_identifier(value: &str) -> String {
    let mut output = String::new();
    let mut capitalize = true;
    for character in value.chars() {
        if !character.is_ascii_alphanumeric() {
            capitalize = true;
            continue;
        }
        if capitalize {
            output.push(character.to_ascii_uppercase());
            capitalize = false;
        } else {
            output.push(character);
        }
    }
    if output.is_empty() {
        output.push_str("Type");
    }
    if output.starts_with(|character: char| character.is_ascii_digit()) {
        output.insert(0, 'T');
    }
    output
}

fn unique_c_identifier(value: &str, used: &mut HashSet<String>) -> String {
    let base = c_identifier(value);
    if used.insert(base.clone()) {
        return base;
    }
    let mut suffix = 2usize;
    loop {
        let candidate = format!("{base}_{suffix}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        suffix += 1;
    }
}

fn c_identifier(value: &str) -> String {
    let mut identifier = String::with_capacity(value.len());
    for (index, character) in value.chars().enumerate() {
        let valid = if index == 0 {
            character.is_ascii_alphabetic() || character == '_'
        } else {
            character.is_ascii_alphanumeric() || character == '_'
        };
        identifier.push(if valid { character } else { '_' });
    }
    if identifier.is_empty() {
        identifier.push_str("value");
    }
    if is_c_keyword(&identifier) {
        identifier.push('_');
    }
    identifier
}

fn header_guard(header_file_name: &str) -> String {
    let mut guard = String::from("ORI_");
    for character in header_file_name.chars() {
        if character.is_ascii_alphanumeric() {
            guard.push(character.to_ascii_uppercase());
        } else {
            guard.push('_');
        }
    }
    guard.push_str("_INCLUDED");
    guard
}

fn is_c_keyword(identifier: &str) -> bool {
    matches!(
        identifier,
        "auto"
            | "break"
            | "case"
            | "char"
            | "const"
            | "continue"
            | "default"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "extern"
            | "float"
            | "for"
            | "goto"
            | "if"
            | "inline"
            | "int"
            | "long"
            | "register"
            | "restrict"
            | "return"
            | "short"
            | "signed"
            | "sizeof"
            | "static"
            | "struct"
            | "switch"
            | "typedef"
            | "union"
            | "unsigned"
            | "void"
            | "volatile"
            | "while"
            | "_Alignas"
            | "_Alignof"
            | "_Atomic"
            | "_Bool"
            | "_Complex"
            | "_Generic"
            | "_Imaginary"
            | "_Noreturn"
            | "_Static_assert"
            | "_Thread_local"
            | "alignas"
            | "alignof"
            | "and"
            | "and_eq"
            | "asm"
            | "bitand"
            | "bitor"
            | "bool"
            | "catch"
            | "char8_t"
            | "char16_t"
            | "char32_t"
            | "class"
            | "compl"
            | "concept"
            | "const_cast"
            | "constexpr"
            | "consteval"
            | "constinit"
            | "co_await"
            | "co_return"
            | "co_yield"
            | "decltype"
            | "delete"
            | "dynamic_cast"
            | "explicit"
            | "export"
            | "false"
            | "friend"
            | "mutable"
            | "namespace"
            | "new"
            | "noexcept"
            | "not"
            | "not_eq"
            | "nullptr"
            | "operator"
            | "or"
            | "or_eq"
            | "private"
            | "protected"
            | "public"
            | "reinterpret_cast"
            | "requires"
            | "static_assert"
            | "static_cast"
            | "template"
            | "this"
            | "thread_local"
            | "throw"
            | "true"
            | "try"
            | "typeid"
            | "typename"
            | "using"
            | "virtual"
            | "wchar_t"
            | "xor"
            | "xor_eq"
    )
}

#[cfg(test)]
mod tests {
    use super::{c_identifier, header_guard, pascal_case_identifier};

    #[test]
    fn converts_ori_names_to_portable_c_identifiers() {
        assert_eq!(pascal_case_identifier("point_data"), "PointData");
        assert_eq!(c_identifier("switch"), "switch_");
        assert_eq!(c_identifier("score-value"), "score_value");
        assert_eq!(
            header_guard("libscore-api.h"),
            "ORI_LIBSCORE_API_H_INCLUDED"
        );
    }
}
